parameters:
    NeptuneVs_main.parametre.class: NeptuneVs\Bundle\MainBundle\Services\ParamService
    
services:
    param:
        class: %NeptuneVs_main.parametre.class%
        arguments: [@doctrine.orm.entity_manager]