parameters:
#    neptune_vs_user.example.class: NeptuneVs\Bundle\UserBundle\Example

services:
#    neptune_vs_user.example:
#        class: %neptune_vs_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
