services:
    NeptuneVs_user.profile.form.type:
        class: NeptuneVs\Bundle\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: NeptuneVs_user_profile }
            
    NeptuneVs_user.registration.form.type:
        class: NeptuneVs\Bundle\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: NeptuneVs_user_registration }        
    NeptuneVs_user.my_provider:
        class: NeptuneVs\Bundle\UserBundle\Provider\MyProvider
        public: false
        arguments: ["@fos_user.user_manager"]